inherit_from:
  - '.rubocop-performance.yml'
  - '.rubocop-rails.yml'
  - '.rubocop-rspec.yml'

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0
  Exclude:
    - '**/db/migrate/*'
    - 'db/schema.rb'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/rails'
    - '**/vendor/**/*'
    - '**/spec_helper.rb'
    - '**/rails_helper.rb'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/initializers/*'
  
RSpec/MultipleExpectations:
  Enabled: false
  
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false